[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"


[functions]
  timeout = 30  # Aumentar a 30 segundos (máximo permitido)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
