[build]
  publish = "public"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Configuración de timeout global
[build.processing.functions]
  timeout = 30
